const items = [
    {
        id: '001',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqNCbPAromDRjQI6jRtLBcOpvYen1fgrqZUg&usqp=CAU',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'https://render.fineartamerica.com/images/rendered/default/t-shirt/23/5/images/artworkimages/medium/2/best-upsc-coaching-center-in-patna-download-the-report-mukesh-kumar.jpg?targetx=0&targety=0&imagewidth=430&imageheight=248&modelwidth=430&modelheight=575',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTydAmBtYQRgIe577OnLqZIdv5BlJHqr7csuw&usqp=CAU',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-3MrXY5x8p2ZPlC87LyUbFKIVBwiYZgiwzXV4Z2eDUjc2QdGKlRlGZikV8dFW1jkkexI&usqp=CAU"',
        company: 'Boat Watch',
        item_name: 'Black Color Fit Icon 2 Calling Smartwatch',
        original_price: 5999,
        current_price: 1399 ,
        discount_percentage: 4600,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 3900,
        },
    },
    {
        id: '005',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP_9bWnOsD0Y2vfoknsrJKMIaFdIxkwxK0yQ&usqp=CAU',
        company: 'DressBerry',
        item_name: 'Maroon Lace Underwired Lightly Padded Push-Up Bra DB-DR-BRA-022B',
        original_price: 899,
        current_price: 350,
        discount_percentage: 61,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 8000,
        },
    },
    {
        id: '006',
        image: 'https://images.pexels.com/photos/10983783/pexels-photo-10983783.jpeg?cs=srgb&dl=pexels-the-glorious-studio-10983783.jpg&fm=jpg',
        company: 'OOMPH',
        item_name: 'Gold-Toned & Pink Meenakari Enamel Pearls Ethnic Jhumka',
        original_price: 3715,
        current_price: 480,
        discount_percentage: 3250,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1700,
        },
    },
    {
        id: '007',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD71ZEULGtQ0pqItrUtpKpKjrV0jvNubjJjg&usqp=CAU',
        company: 'Red Tape',
        item_name: 'Men Beige Padded Jacket',
        original_price: 6599,
        current_price: 1979,
        discount_percentage: 70,
        rating: {
            stars: 4.2,
            count: 318,
        },
    },
    {
        id: '008',
        image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/585e2cd2-4f2a-408c-a8ba-f89952cdf332/revolution-6-road-running-shoes-NC0P7k.png',
        company: 'Nike',
        item_name: 'Men Downshifter 11 Road Running Shoes',
        original_price: 3995,
        current_price: 3995,
        discount_percentage:0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];